AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SafeSakhi - AI-powered women's safety platform

Globals:
  Function:
    Timeout: 30
    Runtime: python3.9
    MemorySize: 256
    Tracing: Active

Resources:

  ##########################
  # Lambda Functions
  ##########################

  AudioProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SafeSakhi-AudioProcessor
      CodeUri: ../lambdas/audio_processor/
      Handler: handler.lambda_handler
      Events:
        AudioTrigger:
          Type: Api
          Properties:
            Path: /audio
            Method: POST
      Environment:
        Variables:
          DYNAMODB_TABLE: SafeSakhi-AudioAnalysis
          S3_BUCKET: safesakhi-audio-temp
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
        - AWSLambdaBasicExecutionRole

  MotionAnalyzerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SafeSakhi-MotionAnalyzer
      CodeUri: ../lambdas/motion_analyzer/
      Handler: handler.lambda_handler
      Events:
        MotionTrigger:
          Type: Api
          Properties:
            Path: /motion
            Method: POST
      Environment:
        Variables:
          DYNAMODB_TABLE: SafeSakhi-MotionAnalysis
      Policies:
        - AmazonDynamoDBFullAccess

  TextAnalyzerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SafeSakhi-TextAnalyzer
      CodeUri: ../lambdas/text_analyzer/
      Handler: handler.lambda_handler
      Events:
        TextTrigger:
          Type: Api
          Properties:
            Path: /text
            Method: POST
      Environment:
        Variables:
          DYNAMODB_TABLE: SafeSakhi-TextAnalysis
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess

  RiskAssessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SafeSakhi-RiskAssessment
      CodeUri: ../lambdas/risk_assessor/
      Handler: handler.lambda_handler
      Environment:
        Variables:
          DYNAMODB_USERS: SafeSakhi-Users
          DYNAMODB_ANALYSIS: SafeSakhi-RiskAssessments
      Policies:
        - AmazonDynamoDBFullAccess
        - LambdaInvokePolicy:
            FunctionName: !GetAtt EmergencyResponderFunction.Arn

  EmergencyResponderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SafeSakhi-EmergencyResponse
      CodeUri: ../lambdas/emergency_responder/
      Handler: handler.lambda_handler
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref EmergencySNSTopic
          S3_BUCKET: safesakhi-evidence-store
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonSNSFullAccess
        - AmazonS3FullAccess

  ##########################
  # DynamoDB Tables
  ##########################

  AudioAnalysisTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SafeSakhi-AudioAnalysis
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE

  MotionAnalysisTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SafeSakhi-MotionAnalysis
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE

  TextAnalysisTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SafeSakhi-TextAnalysis
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE

  RiskAssessmentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SafeSakhi-RiskAssessments
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SafeSakhi-Users
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH

  EvidenceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SafeSakhi-Evidence
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: evidence_id
          AttributeType: S
      KeySchema:
        - AttributeName: evidence_id
          KeyType: HASH

  ##########################
  # S3 Buckets
  ##########################

  TempAudioBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: safesakhi-audio-temp

  EvidenceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: safesakhi-evidence-store

  ##########################
  # SNS Topic
  ##########################

  EmergencySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: SafeSakhi-EmergencyAlerts

  ##########################
  # Outputs
  ##########################

Outputs:
  ApiURL:
    Description: "API Gateway endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  AudioAnalysisTable:
    Value: !Ref AudioAnalysisTable
  MotionAnalysisTable:
    Value: !Ref MotionAnalysisTable
  TextAnalysisTable:
    Value: !Ref TextAnalysisTable
  RiskAssessmentsTable:
    Value: !Ref RiskAssessmentsTable
  EvidenceS3Bucket:
    Value: !Ref EvidenceBucket
  EmergencyAlertsTopic:
    Value: !Ref EmergencySNSTopic